# resolve-type-names: false

interface ::_RbsRailsPathHelpers
  def auth_google_one_tap_path: (*untyped) -> ::String
  def session_handoff_path: (*untyped) -> ::String
  def invitation_acceptance_path: (*untyped) -> ::String
  def invitations_path: (*untyped) -> ::String
  def agreement_path: (*untyped) -> ::String
  def accept_agreement_path: (*untyped) -> ::String
  def account_path: (*untyped) -> ::String
  def mcp_path: (*untyped) -> ::String
  def mcp_uploads_path: (*untyped) -> ::String
  def transition_move_box_path: (*untyped) -> ::String
  def duplicate_move_box_path: (*untyped) -> ::String
  def fragile_move_box_path: (*untyped) -> ::String
  def seal_move_box_path: (*untyped) -> ::String
  def description_suggestion_move_box_path: (*untyped) -> ::String
  def move_box_items_path: (*untyped) -> ::String
  def new_move_box_item_path: (*untyped) -> ::String
  def move_box_review_path: (*untyped) -> ::String
  def move_box_review_photo_path: (*untyped) -> ::String
  def move_box_review_mark_reviewed_path: (*untyped) -> ::String
  def move_box_review_rename_item_path: (*untyped) -> ::String
  def move_box_review_remove_item_path: (*untyped) -> ::String
  def move_box_review_add_item_path: (*untyped) -> ::String
  def move_box_review_move_photo_path: (*untyped) -> ::String
  def move_box_review_retake_photo_path: (*untyped) -> ::String
  def move_box_recovery_photo_path: (*untyped) -> ::String
  def move_box_recovery_photo_state_path: (*untyped) -> ::String
  def move_box_recovery_photo_retry_path: (*untyped) -> ::String
  def move_box_capture_path: (*untyped) -> ::String
  def move_box_capture_direct_upload_path: (*untyped) -> ::String
  def move_box_capture_retry_path: (*untyped) -> ::String
  def move_box_label_path: (*untyped) -> ::String
  def move_box_manifest_path: (*untyped) -> ::String
  def move_box_unpacking_path: (*untyped) -> ::String
  def move_box_unpacking_complete_path: (*untyped) -> ::String
  def move_box_unpacking_reopen_path: (*untyped) -> ::String
  def move_box_unpacking_remove_path: (*untyped) -> ::String
  def move_box_unpacking_restore_path: (*untyped) -> ::String
  def move_boxes_path: (*untyped) -> ::String
  def new_move_box_path: (*untyped) -> ::String
  def edit_move_box_path: (*untyped) -> ::String
  def move_box_path: (*untyped) -> ::String
  def move_scan_path: (*untyped) -> ::String
  def move_scan_resolve_path: (*untyped) -> ::String
  def move_move_item_path: (*untyped) -> ::String
  def mark_removed_move_item_path: (*untyped) -> ::String
  def restore_move_item_path: (*untyped) -> ::String
  def generate_image_move_item_path: (*untyped) -> ::String
  def move_item_path: (*untyped) -> ::String
  def move_vocabularies_path: (*untyped) -> ::String
  def move_vocabulary_path: (*untyped) -> ::String
  def move_search_path: (*untyped) -> ::String
  def move_gallery_path: (*untyped) -> ::String
  def move_gallery_group_path: (*untyped) -> ::String
  def move_review_path: (*untyped) -> ::String
  def update_role_move_member_path: (*untyped) -> ::String
  def move_members_path: (*untyped) -> ::String
  def move_member_path: (*untyped) -> ::String
  def resend_move_invitation_path: (*untyped) -> ::String
  def move_invitations_path: (*untyped) -> ::String
  def move_invitation_path: (*untyped) -> ::String
  def move_summary_path: (*untyped) -> ::String
  def move_summary_unit_system_path: (*untyped) -> ::String
  def move_activity_path: (*untyped) -> ::String
  def move_activity_restore_path: (*untyped) -> ::String
  def move_activity_revert_path: (*untyped) -> ::String
  def move_menu_path: (*untyped) -> ::String
  def move_box_steps_path: (*untyped) -> ::String
  def move_label_print_path: (*untyped) -> ::String
  def download_move_label_print_run_path: (*untyped) -> ::String
  def move_label_print_runs_path: (*untyped) -> ::String
  def move_label_print_run_path: (*untyped) -> ::String
  def move_settings_path: (*untyped) -> ::String
  def move_settings_unit_system_path: (*untyped) -> ::String
  def move_settings_auto_confirm_threshold_path: (*untyped) -> ::String
  def move_settings_labels_per_box_path: (*untyped) -> ::String
  def move_settings_provider_key_path: (*untyped) -> ::String
  def move_settings_remove_provider_key_path: (*untyped) -> ::String
  def move_settings_recognition_provider_path: (*untyped) -> ::String
  def move_settings_embedding_provider_path: (*untyped) -> ::String
  def move_integration_tokens_path: (*untyped) -> ::String
  def move_integration_token_path: (*untyped) -> ::String
  def moves_path: (*untyped) -> ::String
  def new_move_path: (*untyped) -> ::String
  def move_path: (*untyped) -> ::String
  def welcome_home_path: (*untyped) -> ::String
  def style_guide_path: (*untyped) -> ::String
  def test_login_path: (*untyped) -> ::String
  def csp_violation_report_path: (*untyped) -> ::String
  def rails_health_check_path: (*untyped) -> ::String
  def pwa_manifest_path: (*untyped) -> ::String
  def pwa_service_worker_path: (*untyped) -> ::String
  def root_path: (*untyped) -> ::String
  def turbo_recede_historical_location_path: (*untyped) -> ::String
  def turbo_resume_historical_location_path: (*untyped) -> ::String
  def turbo_refresh_historical_location_path: (*untyped) -> ::String
  def rails_postmark_inbound_emails_path: (*untyped) -> ::String
  def rails_relay_inbound_emails_path: (*untyped) -> ::String
  def rails_sendgrid_inbound_emails_path: (*untyped) -> ::String
  def rails_mandrill_inbound_health_check_path: (*untyped) -> ::String
  def rails_mandrill_inbound_emails_path: (*untyped) -> ::String
  def rails_mailgun_inbound_emails_path: (*untyped) -> ::String
  def rails_conductor_inbound_emails_path: (*untyped) -> ::String
  def new_rails_conductor_inbound_email_path: (*untyped) -> ::String
  def rails_conductor_inbound_email_path: (*untyped) -> ::String
  def new_rails_conductor_inbound_email_source_path: (*untyped) -> ::String
  def rails_conductor_inbound_email_sources_path: (*untyped) -> ::String
  def rails_conductor_inbound_email_reroute_path: (*untyped) -> ::String
  def rails_conductor_inbound_email_incinerate_path: (*untyped) -> ::String
  def rails_service_blob_path: (*untyped) -> ::String
  def rails_service_blob_proxy_path: (*untyped) -> ::String
  def rails_blob_representation_path: (*untyped) -> ::String
  def rails_blob_representation_proxy_path: (*untyped) -> ::String
  def rails_disk_service_path: (*untyped) -> ::String
  def update_rails_disk_service_path: (*untyped) -> ::String
  def rails_direct_uploads_path: (*untyped) -> ::String
  def rails_representation_path: (*untyped) -> ::String
  def rails_blob_path: (*untyped) -> ::String
  def rails_storage_proxy_path: (*untyped) -> ::String
  def rails_storage_redirect_path: (*untyped) -> ::String
  def auth_google_one_tap_url: (*untyped) -> ::String
  def session_handoff_url: (*untyped) -> ::String
  def invitation_acceptance_url: (*untyped) -> ::String
  def invitations_url: (*untyped) -> ::String
  def agreement_url: (*untyped) -> ::String
  def accept_agreement_url: (*untyped) -> ::String
  def account_url: (*untyped) -> ::String
  def mcp_url: (*untyped) -> ::String
  def mcp_uploads_url: (*untyped) -> ::String
  def transition_move_box_url: (*untyped) -> ::String
  def duplicate_move_box_url: (*untyped) -> ::String
  def fragile_move_box_url: (*untyped) -> ::String
  def seal_move_box_url: (*untyped) -> ::String
  def description_suggestion_move_box_url: (*untyped) -> ::String
  def move_box_items_url: (*untyped) -> ::String
  def new_move_box_item_url: (*untyped) -> ::String
  def move_box_review_url: (*untyped) -> ::String
  def move_box_review_photo_url: (*untyped) -> ::String
  def move_box_review_mark_reviewed_url: (*untyped) -> ::String
  def move_box_review_rename_item_url: (*untyped) -> ::String
  def move_box_review_remove_item_url: (*untyped) -> ::String
  def move_box_review_add_item_url: (*untyped) -> ::String
  def move_box_review_move_photo_url: (*untyped) -> ::String
  def move_box_review_retake_photo_url: (*untyped) -> ::String
  def move_box_recovery_photo_url: (*untyped) -> ::String
  def move_box_recovery_photo_state_url: (*untyped) -> ::String
  def move_box_recovery_photo_retry_url: (*untyped) -> ::String
  def move_box_capture_url: (*untyped) -> ::String
  def move_box_capture_direct_upload_url: (*untyped) -> ::String
  def move_box_capture_retry_url: (*untyped) -> ::String
  def move_box_label_url: (*untyped) -> ::String
  def move_box_manifest_url: (*untyped) -> ::String
  def move_box_unpacking_url: (*untyped) -> ::String
  def move_box_unpacking_complete_url: (*untyped) -> ::String
  def move_box_unpacking_reopen_url: (*untyped) -> ::String
  def move_box_unpacking_remove_url: (*untyped) -> ::String
  def move_box_unpacking_restore_url: (*untyped) -> ::String
  def move_boxes_url: (*untyped) -> ::String
  def new_move_box_url: (*untyped) -> ::String
  def edit_move_box_url: (*untyped) -> ::String
  def move_box_url: (*untyped) -> ::String
  def move_scan_url: (*untyped) -> ::String
  def move_scan_resolve_url: (*untyped) -> ::String
  def move_move_item_url: (*untyped) -> ::String
  def mark_removed_move_item_url: (*untyped) -> ::String
  def restore_move_item_url: (*untyped) -> ::String
  def generate_image_move_item_url: (*untyped) -> ::String
  def move_item_url: (*untyped) -> ::String
  def move_vocabularies_url: (*untyped) -> ::String
  def move_vocabulary_url: (*untyped) -> ::String
  def move_search_url: (*untyped) -> ::String
  def move_gallery_url: (*untyped) -> ::String
  def move_gallery_group_url: (*untyped) -> ::String
  def move_review_url: (*untyped) -> ::String
  def update_role_move_member_url: (*untyped) -> ::String
  def move_members_url: (*untyped) -> ::String
  def move_member_url: (*untyped) -> ::String
  def resend_move_invitation_url: (*untyped) -> ::String
  def move_invitations_url: (*untyped) -> ::String
  def move_invitation_url: (*untyped) -> ::String
  def move_summary_url: (*untyped) -> ::String
  def move_summary_unit_system_url: (*untyped) -> ::String
  def move_activity_url: (*untyped) -> ::String
  def move_activity_restore_url: (*untyped) -> ::String
  def move_activity_revert_url: (*untyped) -> ::String
  def move_menu_url: (*untyped) -> ::String
  def move_box_steps_url: (*untyped) -> ::String
  def move_label_print_url: (*untyped) -> ::String
  def download_move_label_print_run_url: (*untyped) -> ::String
  def move_label_print_runs_url: (*untyped) -> ::String
  def move_label_print_run_url: (*untyped) -> ::String
  def move_settings_url: (*untyped) -> ::String
  def move_settings_unit_system_url: (*untyped) -> ::String
  def move_settings_auto_confirm_threshold_url: (*untyped) -> ::String
  def move_settings_labels_per_box_url: (*untyped) -> ::String
  def move_settings_provider_key_url: (*untyped) -> ::String
  def move_settings_remove_provider_key_url: (*untyped) -> ::String
  def move_settings_recognition_provider_url: (*untyped) -> ::String
  def move_settings_embedding_provider_url: (*untyped) -> ::String
  def move_integration_tokens_url: (*untyped) -> ::String
  def move_integration_token_url: (*untyped) -> ::String
  def moves_url: (*untyped) -> ::String
  def new_move_url: (*untyped) -> ::String
  def move_url: (*untyped) -> ::String
  def welcome_home_url: (*untyped) -> ::String
  def style_guide_url: (*untyped) -> ::String
  def test_login_url: (*untyped) -> ::String
  def csp_violation_report_url: (*untyped) -> ::String
  def rails_health_check_url: (*untyped) -> ::String
  def pwa_manifest_url: (*untyped) -> ::String
  def pwa_service_worker_url: (*untyped) -> ::String
  def root_url: (*untyped) -> ::String
  def turbo_recede_historical_location_url: (*untyped) -> ::String
  def turbo_resume_historical_location_url: (*untyped) -> ::String
  def turbo_refresh_historical_location_url: (*untyped) -> ::String
  def rails_postmark_inbound_emails_url: (*untyped) -> ::String
  def rails_relay_inbound_emails_url: (*untyped) -> ::String
  def rails_sendgrid_inbound_emails_url: (*untyped) -> ::String
  def rails_mandrill_inbound_health_check_url: (*untyped) -> ::String
  def rails_mandrill_inbound_emails_url: (*untyped) -> ::String
  def rails_mailgun_inbound_emails_url: (*untyped) -> ::String
  def rails_conductor_inbound_emails_url: (*untyped) -> ::String
  def new_rails_conductor_inbound_email_url: (*untyped) -> ::String
  def rails_conductor_inbound_email_url: (*untyped) -> ::String
  def new_rails_conductor_inbound_email_source_url: (*untyped) -> ::String
  def rails_conductor_inbound_email_sources_url: (*untyped) -> ::String
  def rails_conductor_inbound_email_reroute_url: (*untyped) -> ::String
  def rails_conductor_inbound_email_incinerate_url: (*untyped) -> ::String
  def rails_service_blob_url: (*untyped) -> ::String
  def rails_service_blob_proxy_url: (*untyped) -> ::String
  def rails_blob_representation_url: (*untyped) -> ::String
  def rails_blob_representation_proxy_url: (*untyped) -> ::String
  def rails_disk_service_url: (*untyped) -> ::String
  def update_rails_disk_service_url: (*untyped) -> ::String
  def rails_direct_uploads_url: (*untyped) -> ::String
  def rails_representation_url: (*untyped) -> ::String
  def rails_blob_url: (*untyped) -> ::String
  def rails_storage_proxy_url: (*untyped) -> ::String
  def rails_storage_redirect_url: (*untyped) -> ::String
end

module ::ActionController
  class ::ActionController::Base
    include ::_RbsRailsPathHelpers
  end
end
