class CreateBoxes < ActiveRecord::Migration[8.1]
  def change
    create_table :boxes, id: :uuid, if_not_exists: true do |t|
      # Same-schema FKs: boxes, moves and rooms are cloned together per tenant.
      t.references :move, null: false, foreign_key: true, type: :uuid
      t.references :room, foreign_key: true, type: :uuid
      # Unique within a Move; generated by default, override allowed on create.
      t.string :number, null: false
      # Permanent opaque token scoped to the Box (not regenerated).
      t.string :qr_token, null: false
      # Canonical metric storage; display conversion from the Move unit system
      # lands with the volume/weight summary (D12).
      t.decimal :length_cm, precision: 8, scale: 2
      t.decimal :width_cm, precision: 8, scale: 2
      t.decimal :height_cm, precision: 8, scale: 2
      t.decimal :weight_kg, precision: 8, scale: 2
      t.string :status, null: false, default: "packing"

      t.timestamps
    end
    add_index :boxes, %i[move_id number], unique: true
    add_index :boxes, :qr_token, unique: true
    add_index :boxes, :status
  end
end
